name: CI-Test

on: [push]

jobs:
  test:
    name: Build and test
    runs-on: macos-latest
    strategy:
        matrix:
          destination:
            - 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
            - 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro'
            - 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro Max'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project YourVoyage.xcodeproj -allowProvisioningUpdates -destination "${destination}" -scheme YourVoyage CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project YourVoyage.xcodeproj -allowProvisioningUpdates -destination "${destination}" -scheme YourVoyage CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
